In [2]:
import pandas as pd
import sys, os, importlib
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..', '..')))
import core
importlib.reload(core)

data = {
    'strain': [
        'wt', '∆ bck2', '∆ ccr4',
        'wt', '∆ bck2', '∆ ccr4',
        'wt', '∆ bck2', '∆ ccr4',
        'wt', '∆ bck2', '∆ ccr4',
        'wt', '∆ bck2', '∆ ccr4',
    ],
    '[2-∆∆Cq]': [
        0.915310625, 0.657775267, 0.660058897,
        0.877010893, 0.554400322, 1.831678964,
        0.842257534, 1.058728985, 0.540487566,
        1.419779282, 0.680971661, 0.500809326,
        1.041743429, 1.191132028, 1.788809804
    ],
}



df = pd.DataFrame(data)
core.run_stats(
    df,
    group_col='strain',
    value_cols='[2-∆∆Cq]',)

================================================================================
Group: 'strain'  |  Value: '[2-∆∆Cq]'

,strain,n,mean,median,skewness,n_outliers (IQR),normality_test,normality_p,normal (p>0.05)
0,wt,5,1.0,0.9,1.16,1,Shapiro-Wilk,0.086691,True
1,∆ bck2,5,0.8,0.7,0.40,0,Shapiro-Wilk,0.268934,True
2,∆ ccr4,5,1.1,0.7,0.39,0,Shapiro-Wilk,0.031291,False

,comparison,n_1,n_2,Welch_t_p,t_p,MannWhitneyU_p,tw_sig (p<0.05),t_sig (p<0.05),MWU_sig (p<0.05)
0,wt vs ∆ bck2,5,5,0.2778,0.2769,0.4206,False,False,False
1,wt vs ∆ ccr4,5,5,0.8945,0.8924,0.6905,False,False,False
2,∆ bck2 vs ∆ ccr4,5,5,0.5054,0.4954,1.0000,False,False,False